[build-system]
requires = ["setuptools", "wheel", "setuptools_scm"]
build-backend = "setuptools.build_meta"


[tool.setuptools_scm]
write_to = "src/scmultiplex/_version.py"

[tool.pytest.ini_options]
log_cli = "True"
log_cli_level = "INFO"
