# Copyright 2024 (C) Friedrich Miescher Institute for Biomedical Research and
# University of Zurich
#
# Original authors:
# Joel Lüthi <joel.luethi@uzh.ch>
#
# This file is part of Fractal and was originally developed by eXact lab S.r.l.
# <exact-lab.it> under contract with Liberali Lab from the Friedrich Miescher
# Institute for Biomedical Research and Pelkmans Lab from the University of
# Zurich.
"""
Fractal task list.
"""
from fractal_tasks_core.dev.task_models import CompoundTask, ParallelTask

# executable relative to base folder to src/scmultiplex folder
# TODO: check CPU and GPU usage for each task and allocate more accurate values

TASK_LIST = [
    CompoundTask(
        name="scMultiplex Calculate Object Linking",
        executable_init="fractal/init_select_multiplexing_pairs.py",
        executable="fractal/calculate_object_linking.py",
        meta_init={"cpus_per_task": 1, "mem": 1000},
        meta={"cpus_per_task": 4, "mem": 16000},
        category="Registration",
        modality="HCS",
        tags=["multiplexing", "2D"],
        docs_info="file:task_info/calculate_object_linking.md",
    ),
    CompoundTask(
        name="scMultiplex Calculate Linking Consensus",
        executable_init="fractal/init_select_reference_knowing_all.py",
        executable="fractal/calculate_linking_consensus.py",
        meta_init={"cpus_per_task": 1, "mem": 1000},
        meta={"cpus_per_task": 4, "mem": 16000},
        category="Registration",
        modality="HCS",
        tags=["multiplexing", "2D", "3D"],
        docs_info="file:task_info/calculate_linking_consensus.md",
    ),
    CompoundTask(
        name="scMultiplex Relabel by Linking Consensus",
        executable_init="fractal/init_select_all_knowing_reference.py",
        executable="fractal/relabel_by_linking_consensus.py",
        meta_init={"cpus_per_task": 1, "mem": 1000},
        meta={"cpus_per_task": 4, "mem": 64000},
        category="Registration",
        modality="HCS",
        tags=["multiplexing", "2D", "3D"],
        docs_info="file:task_info/relabel_by_linking_consensus.md",
    ),
    CompoundTask(
        name="scMultiplex Calculate Platymatch Registration",
        executable_init="fractal/init_select_multiplexing_pairs.py",
        executable="fractal/calculate_platymatch_registration.py",
        meta_init={"cpus_per_task": 1, "mem": 1000},
        meta={"cpus_per_task": 4, "mem": 16000},
        category="Registration",
        modality="HCS",
        tags=["multiplexing", "3D"],
        docs_info="file:task_info/calculate_platymatch_registration.md",
    ),
    CompoundTask(
        name="scMultiplex Surface Mesh Multiscale",
        executable_init="fractal/init_select_reference_knowing_all.py",
        executable="fractal/surface_mesh_multiscale.py",
        meta_init={"cpus_per_task": 1, "mem": 1000},
        meta={"cpus_per_task": 4, "mem": 16000},
        category="Image Processing",
        modality="HCS",
        tags=["3D", "mesh"],
        docs_info="file:task_info/surface_mesh_multiscale.md",
    ),
    CompoundTask(
        name="scMultiplex Segment by Intensity Threshold",
        executable_init="fractal/init_select_many_rounds.py",
        executable="fractal/segment_by_intensity_threshold.py",
        meta_init={"cpus_per_task": 1, "mem": 1000},
        meta={"cpus_per_task": 4, "mem": 16000},
        category="Segmentation",
        modality="HCS",
        tags=["Classical segmentation", "3D"],
        docs_info="file:task_info/segment_by_intensity_threshold.md",
    ),
    CompoundTask(
        name="scMultiplex Spherical Harmonics from Label Image",
        executable_init="fractal/init_select_reference_knowing_all.py",
        executable="fractal/spherical_harmonics_from_labelimage.py",
        meta_init={"cpus_per_task": 1, "mem": 1000},
        meta={"cpus_per_task": 4, "mem": 16000},
        category="Measurement",
        modality="HCS",
        tags=["3D"],
        docs_info="file:task_info/spherical_harmonics_from_label_image.md",
    ),
    CompoundTask(
        name="scMultiplex Mesh Measurements",
        executable_init="fractal/init_select_reference_knowing_all.py",
        executable="fractal/scmultiplex_mesh_measurements.py",
        meta_init={"cpus_per_task": 1, "mem": 1000},
        meta={"cpus_per_task": 4, "mem": 16000},
        category="Measurement",
        modality="HCS",
        tags=["3D", "mesh", "morphology"],
        docs_info="file:task_info/mesh_measurements.md",
    ),
    ParallelTask(
        name="scMultiplex Feature Measurements",
        executable="fractal/scmultiplex_feature_measurements.py",
        meta={"cpus_per_task": 4, "mem": 16000},
        category="Measurement",
        tags=["regionprops", "morphology", "intensity"],
        docs_info="file:task_info/feature_measurements.md",
    ),
    ParallelTask(
        name="scMultiplex Expand Labels",
        executable="fractal/expand_labels.py",
        meta={"cpus_per_task": 4, "mem": 16000},
        category="Image Processing",
        tags=["2D", "3D"],
        docs_info="file:task_info/expand_labels.md",
    ),
    CompoundTask(
        name="scMultiplex Calculate Z-Illumination Correction",
        executable_init="fractal/init_select_single_round.py",
        executable="fractal/calculate_z_illumination_correction.py",
        meta_init={"cpus_per_task": 1, "mem": 1000},
        meta={"cpus_per_task": 4, "mem": 16000},
        category="Image Processing",
        modality="HCS",
        tags=["3D", "illumination correction"],
        docs_info="file:task_info/apply_z_illumination_correction.md",
        input_types=dict(z_illum_corrected=False, is_3D=True),
    ),
    CompoundTask(
        name="scMultiplex Apply Z-Illumination Correction",
        executable_init="fractal/init_select_illumination_round.py",
        executable="fractal/apply_z_illumination_correction.py",
        meta_init={"cpus_per_task": 1, "mem": 1000},
        meta={"cpus_per_task": 4, "mem": 16000},
        category="Image Processing",
        modality="HCS",
        tags=["3D", "illumination correction"],
        docs_info="file:task_info/apply_z_illumination_correction.md",
        input_types=dict(z_illum_corrected=False, is_3D=True),
        output_types=dict(z_illum_corrected=True, is_3D=True),
    ),
    ParallelTask(
        name="scMultiplex Fuse Touching Labels",
        executable="fractal/fuse_touching_labels.py",
        meta={"cpus_per_task": 4, "mem": 16000},
        category="Image Processing",
        tags=["2D"],
        docs_info="file:task_info/fuse_touching_labels.md",
    ),
    ParallelTask(
        input_types=dict(is_3D=True),
        output_types=dict(is_3D=False),
        name="Convert 3D Segmentation to MIP",
        executable="fractal/convert_3d_to_mip.py",
        meta={"cpus_per_task": 2, "mem": 8000},
        tags=[
            "Mixed modality",
            "3D to 2D workflows",
        ],
        docs_info="file:task_info/convert_3d_to_mip.md",
    ),
    ParallelTask(
        name="Build Label Image",
        executable="fractal/build_label_image.py",
        meta={"cpus_per_task": 4, "mem": 36000},
        category="Image Processing",
        tags=["Mixed modality"],
        docs_info="file:task_info/build_label_image.md",
    ),
    ParallelTask(
        name="Annotate Mesh by Child Features",
        executable="fractal/annotate_mesh_by_child_features.py",
        meta={"cpus_per_task": 4, "mem": 12000},
        category="Image Processing",
        tags=["3D", "mesh"],
        docs_info="file:task_info/annotate_mesh_by_child_features.md",
    ),
    ParallelTask(
        name="Cleanup 3D Child Labels",
        executable="fractal/cleanup_3d_child_labels.py",
        meta={"cpus_per_task": 4, "mem": 12000},
        category="Image Processing",
        tags=["3D"],
        docs_info="file:task_info/cleanup_3d_child_labels.md",
    ),
    CompoundTask(
        name="scMultiplex Shift by Shift",
        executable_init="fractal/init_select_multiplexing_pairs.py",
        executable="fractal/shift_by_shift.py",
        meta_init={"cpus_per_task": 1, "mem": 1000},
        meta={"cpus_per_task": 4, "mem": 16000},
        category="Registration",
        modality="HCS",
        tags=["multiplexing", "2D", "3D"],
        docs_info="file:task_info/shift_by_shift.md",
    ),
    CompoundTask(
        name="scMultiplex Calculate Warpfield Registration",
        executable_init="fractal/init_select_multiplexing_pairs.py",
        executable="fractal/calculate_warpfield_registration.py",
        meta_init={"cpus_per_task": 1, "mem": 1000},
        meta={"cpus_per_task": 4, "mem": 16000, "needs_gpu": True},
        category="Registration",
        modality="HCS",
        tags=["multiplexing", "3D"],
        docs_info="file:task_info/calculate_warpfield_registration.md",
        input_types=dict(is_3D=True),
    ),
    CompoundTask(
        name="scMultiplex Apply Warpfield Registration",
        executable_init="fractal/init_select_multiplexing_pairs.py",
        executable="fractal/apply_warpfield_registration.py",
        meta_init={"cpus_per_task": 1, "mem": 1000},
        meta={"cpus_per_task": 4, "mem": 16000, "needs_gpu": True},
        category="Registration",
        modality="HCS",
        tags=["multiplexing", "3D"],
        docs_info="file:task_info/apply_warpfield_registration.md",
        input_types=dict(registered=False, is_3D=True),
        output_types=dict(registered=True, is_3D=True),
    ),
    CompoundTask(
        name="scMultiplex Post Registration Cleanup",
        executable_init="fractal/init_select_all_knowing_reference.py",
        executable="fractal/post_registration_cleanup.py",
        meta_init={"cpus_per_task": 1, "mem": 1000},
        meta={"cpus_per_task": 4, "mem": 16000},
        category="Registration",
        modality="HCS",
        tags=["multiplexing", "3D"],
        docs_info="file:task_info/post_registration_cleanup.md",
        input_types=dict(is_3D=True),
        output_types=dict(registered=True, is_3D=True),
    ),
]
